title: Andrea Pardo
logo: assets/img/bluelogo.png
description: ¡Hola! Gracias por visitar mi portafolio de proyectos de QA engineer.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
